const $=s=>document.querySelector(s), photos=$('#photos'), previews=$('#previews'), music=$('#music'), start=$('#start');
let imgs=[], audio=null, timers=[];
function show(id){document.querySelectorAll('.scene').forEach(x=>x.classList.remove('active'));$('#'+id).classList.add('active')}
const flower=$('#flowerVideo'); flower.addEventListener('ended',()=>show('setup'));
flower.addEventListener('loadedmetadata',()=>{setTimeout(()=>{if($('#opening').classList.contains('active')) flower.play().catch(()=>{});},350)});
window.addEventListener('load',()=>flower.play().catch(()=>{}));
photos.addEventListener('change',e=>{imgs=[...e.target.files].filter(f=>f.type.startsWith('image/')).slice(0,12);previews.innerHTML='';imgs.forEach(f=>{const im=document.createElement('img');im.src=URL.createObjectURL(f);previews.appendChild(im)});start.disabled=imgs.length<1});
music.addEventListener('change',e=>{if(e.target.files[0]){audio=new Audio(URL.createObjectURL(e.target.files[0]));audio.loop=true;}});
function src(i){return URL.createObjectURL(imgs[i%imgs.length])}
function canvas(inner,cls='fade'){return `<div class="canvas ${cls}">${inner}</div>`}
function slideHTML(n){const a=src(n),b=src(n+1),c=src(n+2);switch(n%7){case 0:return canvas(`<div class="bg"></div><div class="word" style="left:8%;top:15%">MADE</div><img class="photo" src="${a}" style="left:20%;top:28%;width:60%;height:45%;border-radius:26px"><div class="script" style="right:10%;bottom:16%">in Japan ♡</div><div class="hat" style="right:7%;top:7%">🎩</div>`,'zoom');case 1:return canvas(`<div class="bg" style="background:linear-gradient(145deg,#d6d0bd,#8d9271)"></div><div class="word" style="right:6%;top:20%;font-size:20vw">IN</div><img class="photo" src="${a}" style="left:7%;top:15%;width:86%;height:62%;border-radius:24px"><div class="script" style="left:9%;bottom:9%">beautiful girl</div>`,'pop');case 2:return canvas(`<div class="bg" style="background:#f2eee8"></div><div class="collage"><img src="${a}"><img src="${b}"><img src="${c}"><img src="${src(n+3)}"></div><div class="heart" style="right:8%;top:6%">♡</div>`,'fade');case 3:return canvas(`<div class="bg"></div><img class="photo" src="${a}" style="left:11%;top:13%;width:78%;height:64%;border-radius:18px"><div class="caption">i fell<br><span style="font-style:italic">deeply</span><br>in love ♡</div>`,'zoom');case 4:return canvas(`<div class="bg" style="background:linear-gradient(135deg,#eee,#fff)"></div><div class="word" style="left:8%;top:10%;font-size:18vw;color:#d88996">JAPAN</div><img class="photo" src="${a}" style="left:16%;top:29%;width:68%;height:48%;border-radius:50%"><div class="script" style="bottom:11%;left:12%">my favourite person</div>`,'pop');case 5:return canvas(`<div class="bg" style="background:#e7a3ae"></div><img class="photo" src="${a}" style="left:7%;top:8%;width:52%;height:42%;border-radius:18px"><img class="photo" src="${b}" style="right:7%;top:31%;width:52%;height:42%;border-radius:18px"><div class="script" style="left:10%;bottom:8%">you ♡ always</div>`,'zoom');default:return canvas(`<div class="bg" style="background:#171317"></div><img class="photo" src="${a}" style="left:12%;top:12%;width:76%;height:58%;border-radius:22px;filter:saturate(.8)"><div class="word" style="left:12%;bottom:18%;font-size:16vw">LOVE</div><div class="heart" style="right:8%;bottom:8%">♥</div>`,'fade')}}
function runEdit(){show('edit'); if(audio){audio.currentTime=0;audio.play().catch(()=>{});}let n=0;function next(){const el=$('#slide');el.innerHTML=slideHTML(n);const bar=$('.progress i');bar.style.transition='none';bar.style.width='0';requestAnimationFrame(()=>{bar.style.transition='width 3.1s linear';bar.style.width='100%'});n++;if(n<14){timers.push(setTimeout(next,3100))}else{timers.push(setTimeout(end,900))}}next()}
function end(){if(audio){audio.pause();}show('ending');const v=$('#endFlower');v.currentTime=0;v.play().catch(()=>{});}
start.addEventListener('click',runEdit);$('#sound').addEventListener('click',()=>{if(!audio)return;if(audio.paused)audio.play();else audio.pause()});$('#again').addEventListener('click',()=>{timers.forEach(clearTimeout);timers=[];show('opening');flower.currentTime=0;flower.play().catch(()=>{});});
